backend:
  name: git-gateway
  repo: vinaypuppal/vinaypuppal.github.io
  branch: gatsbyjs

publish_mode: editorial_workflow

media_folder: "static/assets"

collections:
  - label: "Blog"
    name: "blog"
    folder: "src/content/posts"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Pages"
    name: "pages"
    files:
      - label: "Works Page Content"
        name: "works"
        file: "src/content/works/works.json"
        description: "My Works"
        editor:
          preview: false
        fields:
          - name: "allWorks"
            label: "Works"
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Description, name: description, widget: string}
              - {label: DemoUrl, name: demoUrl, widget: string}
              - {label: PreviewUrl, name: previewUrl, widget: string}
              - {label: Category, name: category, widget: select, options: ['vanilla', 'node', 'react', 'vue']}
      - label: "Site Meta Data"
        name: "metadata"
        file: "src/content/meta-data.yml"
        description: "Meta data of my site"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: SubTitle, name: subtitle, widget: string}
          - label: SocialLinks
            name: socialLinks
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Url, name: url, widget: string}